/**
 * Shared request-handling primitives for API routes: client-IP resolution,
 * authorization gates, and error responses that don't leak internals.
 */
import { NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { IS_PRODUCTION, assertSecureEnv } from "@/lib/security/env";
import { isAdminRole, satisfiesRole, type AdminRole } from "@/lib/security/roles";
import { logSecurityEvent, maskEmail } from "@/lib/security/audit";

export interface AdminIdentity {
  id: string;
  email: string;
  name?: string;
  role: AdminRole;
}

/**
 * Resolves the client IP from proxy headers.
 *
 * `x-forwarded-for` is a comma-separated chain that the client can prepend to,
 * so reading the raw header (or its first entry) lets an attacker rotate their
 * rate-limit bucket at will. On Vercel the platform overwrites `x-real-ip` and
 * appends the true peer address as the LAST entry of `x-forwarded-for`, so the
 * rightmost hop is the only value a client cannot forge.
 */
export function getClientIp(req: Request): string {
  const realIp = req.headers.get("x-real-ip")?.trim();
  if (realIp) return realIp;

  const forwarded = req.headers.get("x-forwarded-for");
  if (forwarded) {
    const hops = forwarded
      .split(",")
      .map((h) => h.trim())
      .filter(Boolean);
    if (hops.length > 0) return hops[hops.length - 1];
  }

  // No proxy headers: everything shares one bucket. That fails closed (stricter
  // limiting) rather than open, which is the right direction for a limiter.
  return "unknown";
}

/**
 * Generic error response. The caught error is logged server-side but never
 * serialized to the client — Mongo/driver messages routinely disclose
 * collection names, query shapes, hostnames and validation internals.
 */
export function serverError(context: string, error: unknown, publicMessage = "Something went wrong. Please try again."): NextResponse {
  console.error(`[${context}]`, error);
  const body: Record<string, string> = { error: publicMessage };
  // Local debugging aid only; never enabled in production.
  if (!IS_PRODUCTION && error instanceof Error) {
    body.debug = error.message;
  }
  return NextResponse.json(body, { status: 500 });
}

export function badRequest(message: string, details?: unknown): NextResponse {
  return NextResponse.json(details === undefined ? { error: message } : { error: message, details }, { status: 400 });
}

/**
 * True for a well-formed MongoDB ObjectId.
 *
 * Route handlers pass `params.id` straight to `findById`. A non-ObjectId segment
 * (`/api/admin/products/notanid`) makes Mongoose throw a CastError, which
 * surfaced as a 500 — indistinguishable in the logs from a genuine server fault,
 * and trivially generated by a scanner walking the API. Callers check this first
 * and return 404 instead.
 */
export function isValidObjectId(id: unknown): id is string {
  return typeof id === "string" && /^[a-f0-9]{24}$/i.test(id);
}

export function notFound(message = "Not found"): NextResponse {
  return NextResponse.json({ error: message }, { status: 404 });
}

/**
 * True for a MongoDB duplicate-key error (E11000).
 *
 * The admin create/update handlers check slug uniqueness with a `findOne` and
 * then write — two concurrent requests both pass the check, and the unique index
 * rejects the loser. Without this, that surfaced as a generic 500 ("Failed to
 * create product") instead of the accurate "name already exists" the first
 * branch would have returned.
 */
export function isDuplicateKeyError(error: unknown): boolean {
  return Boolean(
    error &&
      typeof error === "object" &&
      (error as { code?: unknown }).code === 11000
  );
}

export function unauthorized(): NextResponse {
  return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
}

export function forbidden(): NextResponse {
  return NextResponse.json({ error: "Forbidden" }, { status: 403 });
}

export function tooManyRequests(message = "Too many requests. Please wait and try again.", retryAfterSeconds?: number): NextResponse {
  return NextResponse.json(
    { error: message },
    {
      status: 429,
      headers: retryAfterSeconds ? { "Retry-After": String(Math.max(1, Math.ceil(retryAfterSeconds))) } : undefined,
    }
  );
}

/**
 * Authorization gate for every admin route.
 *
 * The routes previously only checked `if (!session)`, which treats "some valid
 * session exists" as "is an administrator". This verifies the session carries a
 * recognised admin role, so adding any non-admin session type later cannot
 * silently grant access to the admin API.
 *
 * Returns either the caller's identity or the response to send back.
 */
export async function requireAdmin(
  /**
   * Minimum privilege required. "admin" accepts any admin role; "superadmin"
   * requires an elevated one (which `owner` also satisfies).
   */
  options: { role?: "admin" | "superadmin" } = {}
): Promise<{ admin: AdminIdentity } | { response: NextResponse }> {
  // Request-time environment check: a production deploy with a missing or weak
  // NEXTAUTH_SECRET must not be able to serve authenticated admin traffic, since
  // session tokens would be forgeable.
  assertSecureEnv();

  const session = await getServerSession(authOptions);

  const user = session?.user as { id?: string; email?: string; name?: string; role?: string } | undefined;
  if (!session || !user?.email) {
    return { response: unauthorized() };
  }

  const role = user.role;
  if (!isAdminRole(role)) {
    logSecurityEvent("authz.denied", {
      actor: maskEmail(user.email),
      reason: `unrecognised_role:${String(role)}`,
    });
    return { response: forbidden() };
  }

  if (!satisfiesRole(role, options.role ?? "admin")) {
    logSecurityEvent("authz.denied", {
      actor: maskEmail(user.email),
      reason: `insufficient_role:${role}`,
    });
    return { response: forbidden() };
  }

  return {
    admin: {
      id: String(user.id ?? ""),
      email: String(user.email),
      name: user.name ? String(user.name) : undefined,
      role,
    },
  };
}

/** Narrowing helper so call sites read as `if (isDenied(auth)) return auth.response;` */
export function isDenied(
  result: { admin: AdminIdentity } | { response: NextResponse }
): result is { response: NextResponse } {
  return "response" in result;
}

/**
 * Reads and size-caps a JSON body.
 *
 * `req.json()` will happily buffer whatever the platform accepts, so an
 * oversized body burns memory and CPU before any validation runs.
 */
export async function readJsonBody<T = unknown>(
  req: Request,
  maxBytes = 100 * 1024
): Promise<{ ok: true; data: T } | { ok: false; response: NextResponse }> {
  const tooLarge = {
    ok: false as const,
    response: NextResponse.json({ error: "Request body too large." }, { status: 413 }),
  };

  // Fast path: trust a declared length that is already over the cap.
  const declaredLength = Number(req.headers.get("content-length") ?? "0");
  if (Number.isFinite(declaredLength) && declaredLength > maxBytes) {
    return tooLarge;
  }

  // Slow path: read the stream and abort as soon as the cap is passed.
  //
  // `await req.text()` was used here, which only enforced the cap AFTER the
  // whole body had been buffered. `Content-Length` is absent on a chunked
  // request, so the fast path above could be skipped entirely and an arbitrarily
  // large body would be held in memory before being rejected — the cap was
  // advisory rather than enforced. Reading incrementally makes it a real bound.
  let raw: string;
  try {
    const body = req.body;
    if (!body) {
      raw = "";
    } else {
      const reader = body.getReader();
      const chunks: Uint8Array[] = [];
      let received = 0;

      for (;;) {
        const { done, value } = await reader.read();
        if (done) break;
        if (!value) continue;

        received += value.byteLength;
        if (received > maxBytes) {
          // Stop pulling and release the connection rather than draining it.
          await reader.cancel().catch(() => {});
          return tooLarge;
        }
        chunks.push(value);
      }

      raw = new TextDecoder().decode(
        chunks.length === 1 ? chunks[0] : Buffer.concat(chunks.map((c) => Buffer.from(c)))
      );
    }
  } catch {
    return { ok: false, response: badRequest("Could not read request body.") };
  }

  try {
    const parsed = JSON.parse(raw) as T;
    // Reject a JSON scalar/null where an object is expected, so callers can
    // safely do `parsed.data?.field` without a runtime surprise.
    if (parsed === null || typeof parsed !== "object") {
      return { ok: false, response: badRequest("Expected a JSON object body.") };
    }
    return { ok: true, data: parsed };
  } catch {
    return { ok: false, response: badRequest("Invalid JSON body.") };
  }
}
